name: Export BloodHound Images

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Pull images
        run: |
          docker pull postgres:18
          docker pull neo4j:4.4
          docker pull specterops/bloodhound:latest

      - name: Save images
        run: |
          docker save \
            postgres:18 \
            neo4j:4.4 \
            specterops/bloodhound:latest \
            -o bloodhound-images.tar

      - name: Compress
        run: |
          gzip bloodhound-images.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bloodhound-images
          path: bloodhound-images.tar.gz
          retention-days: 30
